name = "BayesNets"
uuid = "ba4760a4-c768-5bed-964b-cf806dc591cb"
version = "3.3.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Discretizers = "6e83dbb3-75ca-525b-8ae2-3751f0dd50b4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = "0.21,0.22"
DataStructures = "0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.18"
Discretizers = "3.0"
Distributions = "0.17,0.18,0.19,0.20,0.21,0.22,0.23,0.24"
GraphPlot = "0.3,0.3.1,0.4,0.4.1"
IterTools = "1.3"
LightGraphs = "1.0"
LightXML = "0.8,0.9"
NBInclude = "2.0"
Parameters = "0.10,0.11,0.12"
RDatasets = "0.5,0.6"
Reexport = "0.2"
Requires = "1.0.1"
SpecialFunctions = "0.8,0.10,1.0,1.1,1.2"
StatsBase = "0.25,0.26,0.27,0.28,0.29,0.30,0.31,0.32,0.33"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"

[targets]
test = ["Statistics", "NBInclude", "LinearAlgebra", "Test", "RDatasets", "Random", "TikzGraphs"]
